model:
  dragonnet:
    latent_size: 50
    hidden_size: 50
    cov_dim: 100
  transtee:
    latent_size: 50
    hidden_size: 50
    cov_dim: 100
  ours:
    hidden_size: 50
    latent_size: 50
  nam:
    hidden_size: 50
    latent_size: 50


rl:
  dqn:
    mem_sample_size: 2
    replay_memory_capacity: 5000
    epsilon: 0.2
    epsilon_falloff: 0.9
    gamma: 0.999
    target_update: 20
    discretize_feat_value_count: 50